### ISSUE TITLE
Error while copying text

### ISSUE THREAD

**Issue by taneltm** [slap-editor/slap#125]
Version: 0.1.3
OS: Ubuntu

XCLIP not installed.
XCLIPBOARD is installed.

Steps to reproduce:
* Open a file in slap
* Use shift+arrows to select text
* Hit Ctrl+C

Expected result:
* Selected text to be copied to the clipboard or give notice about why text cannot be copied

Actual result:
* Error

```
^--- With additional stack trace: Error: write EPIPE
  at errnoException (net.js:905:11)
  at Object.afterWrite (net.js:721:19)
From previous event:
  at Object.ret [as copyAsync] (<anonymous>:7:21)
  at Editor.<anonymous> (/home/tan/npm/lib/node_modules/slap/node_modules/slap-clipboard-plugin/index.js:17:33)
From previous event:
  at Editor.<anonymous> (/home/tan/npm/lib/node_modules/slap/node_modules/slap-clipboard-plugin/index.js:56:14)
  at Editor.EventEmitter._emit (/home/tan/npm/lib/node_modules/slap/node_modules/blessed/lib/events.js:90:20)
  at Editor.EventEmitter.emit (/home/tan/npm/lib/node_modules/slap/node_modules/blessed/lib/events.js:106:12)
  at Program.<anonymous> (/home/tan/npm/lib/node_modules/slap/node_modules/blessed/lib/widget.js:578:15)
  at Program.emit (events.js:98:17)
  at ReadStream.<anonymous> (/home/tan/npm/lib/node_modules/slap/node_modules/blessed/lib/program.js:274:10)
  at ReadStream.emit (events.js:98:17)
  at emitKey (readline.js:1096:12)
  at ReadStream.onData (readline.js:841:14)
  at ReadStream.emit (events.js:117:20)
  at ReadStream.<anonymous> (_stream_readable.js:765:14)
  at ReadStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at ReadStream.Readable.push (_stream_readable.js:128:10)
  at TTY.onread (net.js:529:21)

```

**Comment by secrettriangle** [comment]
Sorry this was lying around for so long, I haven't used Ubuntu since before I moved to a different city. I just installed Ubuntu for something else -- first thing I did was install slap and try to copy something.

*Crash*

Should be fixed as of slap-editor/slap-clipboard-plugin@240d5d4. Please confirm!
