### ISSUE TITLE
Slap wont start: "Error: Not a terminal."

### ISSUE THREAD

**Issue by ViktorNova** [slap-editor/slap#134]
I've been happily using slap on Arch linux for quite some time, but recently it stopped working. I am now getting this error when starting it

````
^--- With additional stack trace: Error: Not a terminal.                                                                        
    at Program.listen (/usr/lib/node_modules/slap/node_modules/blessed/lib/program.js:260:11)                                   
    at new Program (/usr/lib/node_modules/slap/node_modules/blessed/lib/program.js:108:8)                                       
    at Program (/usr/lib/node_modules/slap/node_modules/blessed/lib/program.js:30:12)                                           
    at Slap.Screen (/usr/lib/node_modules/slap/node_modules/blessed/lib/widget.js:257:20)                                       
    at new Slap (/usr/lib/node_modules/slap/lib/ui/Slap.js:17:18)                                                               
    at /usr/lib/node_modules/slap/lib/cli.js:69:16                                                                              
    at tryCatcher (/usr/lib/node_modules/slap/node_modules/bluebird/js/main/util.js:24:31)                                      
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/slap/node_modules/bluebird/js/main/promise.js:454:31)           
    at Promise._settlePromiseAt (/usr/lib/node_modules/slap/node_modules/bluebird/js/main/promise.js:530:18)                    
    at Promise._settlePromises (/usr/lib/node_modules/slap/node_modules/bluebird/js/main/promise.js:646:14)                     
    at Async._drainQueue (/usr/lib/node_modules/slap/node_modules/bluebird/js/main/async.js:79:16)                              
    at Async._drainQueues (/usr/lib/node_modules/slap/node_modules/bluebird/js/main/async.js:89:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/slap/node_modules/bluebird/js/main/async.js:14:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
````

I am in fact running this in a bash terminal, and have node 12.0
Would be happy to  provide any other information you like

**Comment by secrettriangle** [comment]
What terminal program are you using? Try running `node -p "process.stdin.isTTY"` in your terminal. If it outputs anything other than `true`, try another terminal application such as GNOME Terminal. Your terminal program probably doesn't support [chjj/blessed](https://github.com/chjj/blessed), the library that slap uses to render to the terminal.

**Comment by chjj** [comment]
Very odd. Blessed only throws that error if stdin or stdout is not a tty file descriptor. 

Could I get the exact circumstances of how you ran slap and what terminal/os/etc you're using?

(As an aside, I'm looking to revamp error handling in blessed. Particularly the fallback when the user does not have the required terminfo. Blessed either throws or falls back to xterm depending on the option. ncurses, on the other hand, displays a warning before fallback, which I think is the right way to go).

**Comment by simonhochrein** [comment]
Blessed works best in xterm-256-color
Gnome terminal works well with slap
