### ISSUE TITLE
Installation: missing module error shown during installation

### ISSUE THREAD

**Issue by skatkov** [slap-editor/slap#146]
I've tried using npm and curl to install slap, but both ways ended up with same error appearing:
```
 curl -sL https://raw.githubusercontent.com/slap-editor/slap/master/install.sh | sh
# Installing slap...

module.js:340
    throw err;
          ^
Error: Cannot find module 'child-process-close'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/npm/lib/npm.js:15:1
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:474:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```
```
node -v
v0.10.28
```

**Comment by secrettriangle** [comment]
Hmm, strange... What npm version? Can you pastebin the whole traceback in a gist?

I just tried to install it on node 0.10.28 and npm 1.4.9, worked fine.

**Comment by skatkov** [comment]
Thanks for your promt answer. 

I've looked into this, and it seems that this error comes from my npm. I've had multiple version of npm conflicting with each other, i had to wipe everything related to npm and do a clean install.

And it worked. slap is installed too.
