### ISSUE TITLE
pathwatcher.node is missing

### ISSUE THREAD

**Issue by kookerus** [slap-editor/slap#173]
Recently installed nodejs and slap on a fresh install of Ubuntu 14.04. I tried running slap today, and I get an error saying:

```
module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/pathwatcher.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/text-buffer/node_modules/pathwatcher/lib/main.js:207:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/text-buffer/lib/text-buffer.js:13:10)
    at Object.<anonymous> (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/text-buffer/lib/text-buffer.js:1387:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```
I've tried using npm to install pathwatcher, but no luck.

**Comment by kookerus** [comment]
Reinstalling fixed the issue, apparently. No idea why, though.

**Comment by naomik** [comment]
I was running into this same problem and couldn't figure it out to save my life. However, for me, attempts to reinstall did not fix my issue. Instead, I learned that my server was **running out of memory** while trying to compile slap's native extensions.

For those that are having this problem, please see [my solution](https://github.com/slap-editor/slap/issues/211#issuecomment-152335423) posted on #211

**Comment by dbkaplun** [comment]
It's likely the reason is that your computer is missing some important compilers and libraries for node to build some native extensions. If you're on Ubuntu:
```sh
sudo apt-get install build-essential
```

**Comment by TobiaszCudnik** [comment]
Some here `Error: Cannot find module '../build/Release/pathwatcher.node'`

Remove & install didnt help. No warning msgs.

Macos high sierra, xcode installed.
