### ISSUE TITLE
Error starting slap-editor on windows 10 using babun terminal and cygwin

### ISSUE THREAD

**Issue by didibus** [slap-editor/slap#266]
I'm trying to run slap-editor on windows 10 in babun with cygwin and I get the following error when starting slap:

```
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: ENOENT, no such file or directory 'C:\dev\tty'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.<anonymous> (C:\Users\didier\AppData\Roaming\npm\node_modules\slap\node_modules\ttys\index.js:9:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\didier\AppData\Roaming\npm\node_modules\slap\lib\cli.js:6:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by Paradoxis** [comment]
+1

**Comment by KirkHadley** [comment]
fwiw, it runs straight outta the box in bash on windows using the latest stable 10 build.
