### ISSUE TITLE
slap crashes on RHEL5 when trying to read a file

### ISSUE THREAD

**Issue by didibus** [slap-editor/slap#268]
Every time I try to load a file in slap, it crashes with:

```
Unhandled rejection ReferenceError: Promise is not defined
    at File.module.exports.File.read (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:298:23)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContents (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/text-buffer/lib/text-buffer.js:1093:29)
    at TextBuffer.module.exports.TextBuffer.load (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/text-buffer/lib/text-buffer.js:1154:19)
    at /usr/lib/node_modules/slap/node_modules/editor-widget/lib/Editor.js:74:69
    at Object.finallyHandler (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/base-widget/node_modules/bluebird/js/release/finally.js:44:23)
    at Object.tryCatcher (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/base-widget/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/base-widget/node_modules/bluebird/js/release/promise.js:488:31)
    at Promise._settlePromise (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/base-widget/node_modules/bluebird/js/release/promise.js:545:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/base-widget/node_modules/bluebird/js/release/promise.js:590:10)
    at Promise._settlePromises (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/base-widget/node_modules/bluebird/js/release/promise.js:673:18)
    at Async._drainQueue (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/base-widget/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/base-widget/node_modules/bluebird/js/release/async.js:135:10)
    at Async.drainQueues (/usr/lib/node_modules/slap/node_modules/editor-widget/node_modules/base-widget/node_modules/bluebird/js/release/async.js:16:14)
    at process._tickCallback (node.js:448:13)
```

I'm running slap on RHEL 5 with Node v0.10.41

**Comment by dbkaplun** [comment]
Looks like that version of atom/text-buffer depends on `Promise` being built-in, which is only in ES6+. You're running Node 0.10 which is pretty ancient these days and is ES5 only. You can upgrade to Node 4.x or 5.x using `n`:
```sh
npm install -g n
n use stable # this will install the current LTS release of NodeJS and replace `/usr/bin/node` with a symlink to it
npm install -g npm # ensures npm is latest version
npm install -g slap
```

If you are adamant about not installing a more recent version of NodeJS, you can modify the source code in your slap installation's [lib/cli.js](https://github.com/slap-editor/slap/blob/master/lib/cli.js#L62):

Change
```js
var Promise = require('bluebird');
```
to
```js
global.Promise = require('bluebird');
```
This will polyfill `Promise` with bluebird's implementation for use by atom/text-buffer. (A PR for this would be welcome!)

**Comment by didibus** [comment]
That worked, I made a PR for it: https://github.com/slap-editor/slap/pull/271
