### ISSUE TITLE
Getting more done in GitHub with ZenHub

### ISSUE THREAD

**Issue by largesoft** [slap-editor/slap#286]
Hola! @largesoft has created a [ZenHub](http://www.zenhub.io) account for the **slap-editor** organization. ZenHub is the leading team collaboration and project management solution built for GitHub.

----

#### How do I use ZenHub?

To get set up with ZenHub, all you have to do is **[download the browser extension](https://www.zenhub.io?utm_source=ZHOnboarding)** and log in with your GitHub account. Once you do, you’ll get access to ZenHub’s complete feature-set immediately.

#### What can ZenHub do?

ZenHub adds a series of enhancements directly inside the GitHub UI:

- Real-time, customizable task boards for GitHub issues;
- Burndown charts, estimates, and velocity tracking based on GitHub Milestones;
- Personal to-do lists and task prioritization;
- “+1” button for GitHub issues and comments;
- Drag-and-drop file sharing;
- Time-saving shortcuts like a quick repo switcher.

### [Add ZenHub to GitHub](https://www.zenhub.io?utm_source=ZHOnboarding)

_Still curious? See [more ZenHub features](https://www.zenhub.io/features?utm_source=ZHOnboarding) or read [user reviews](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/reviews). This issue was written by your friendly ZenHub bot, posted by request from @largesoft._

![ZenHub Board](https://cloud.githubusercontent.com/assets/8771909/11153956/233ac4a8-89f1-11e5-94b1-1569d3f38b4d.png)

**Comment by largesoft** [comment]
bash-4.1# echo $CXX
g++-4.8
bash-4.1# sudo npm install -g slap@latest
/usr/local/bin/slap -> /usr/local/lib/node_modules/slap/slap.js

> runas@3.1.1 install /usr/local/lib/node_modules/slap/node_modules/runas
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.4.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/slap/node_modules/runas/.node-gyp"
make: Entering directory `/usr/local/lib/node_modules/slap/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
make: execvp: g++-4.8: Permission denied
make: *** [Release/obj.target/runas/src/main.o] Error 127
make: Leaving directory `/usr/local/lib/node_modules/slap/node_modules/runas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.23.4.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/slap/node_modules/runas
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
/usr/local/lib
+-- (empty)

npm ERR! Linux 2.6.32-504.23.4.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "slap@latest"
npm ERR! node v5.4.1
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/npm/node_modules/npm-debug.log
npm ERR! code 1
bash-4.1#

**Comment by dbkaplun** [comment]
Try `sudo mv /root/.node-gyp /root/.node-gyp.bak` and try again. If that works you shouldn't need that directory around at all but it's up to you if you want to move it back.

**Comment by piranna** [comment]
I'm having the same issue with Node.js 4.4.0

**Comment by piranna** [comment]
Any update on this?

**Comment by dbkaplun** [comment]
@piranna did you try `sudo mv /root/.node-gyp /root/.node-gyp.bak` or removing that dir entirely? Theoretically you need not install with `sudo` but some people have installed other npm packages with `sudo` which would cause problems with a non-sudo install.

**Comment by piranna** [comment]
I'm not using `sudo` at all, and I got this problem both on my machine and on a SemaphoreCI clean instance, so I don't know why it's happening. The most annoying thing is that it fails the first time it try to install it, but when trying to install it second or third time (`runas` is a dependency of several packages) it works :-/

**Comment by dbkaplun** [comment]
Hmm... try removing that dir and installing with sudo, maybe that will help? Could you also post a log for your installation (as it may be different than @disruptiveware's)?

**Comment by teresaejunior** [comment]
Here is the complete build log failing with the runas error: [npm-debug.txt](https://github.com/slap-editor/slap/files/264787/npm-debug.txt)

Thank you for your attention!

**Comment by Fedreg** [comment]
same problem.  Latest node & npm.   Tried moving the node-gyp file and that file could not be found.  Any suggestions?  -Thanks!!

**Comment by lscoughlin** [comment]
If you're on a platform which packages node executable as nodejs ( ubuntu 16.04 LTS for example ) you need to apt install node-legacy package first.

**Comment by dimensi0n** [comment]
Same issue on manjaro linux and ubuntu mate 18.04

**Comment by andyhasit** [comment]
I have a similar issue. Linux Mint 18.0  npm@6.4.1

```
$ sudo npm install -g slap@latest/usr/local/bin/slap -> /usr/local/lib/node_modules/slap/slap.js

> marker-index@4.0.0 install /usr/local/lib/node_modules/slap/node_modules/marker-index
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/slap/node_modules/marker-index/build'
gyp ERR! System Linux 4.4.0-53-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/slap/node_modules/marker-index
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! marker-index@4.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the marker-index@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andrew/.npm/_logs/2018-12-29T23_50_42_902Z-debug.log
```

I tried `apt install node-legacy` but it doesn't exist. I also tried creating the directories manually ahead of installation. Any help on this?
