### ISSUE TITLE
can't use nam to install slap (npm install -g slap@latest),I don't know why?

### ISSUE THREAD

**Issue by JarrarOS** [slap-editor/slap#307]
npm ERR! Linux 3.13.0-65-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "slap@latest"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20

npm ERR! shasum check failed for /tmp/npm-4481-b95ec19e/registry.npmjs.org/slap/-/slap-0.1.60.tgz
npm ERR! Expected: 3ab23a00d22ac77607a0808b11b2eb1b6e395d3d
npm ERR! Actual:   dabba66cb07e7f9dc5351d26f9ab1cb23e32533d
npm ERR! From:     https://registry.npmjs.org/slap/-/slap-0.1.60.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/root/npm-debug.log
[npm-debug_log.txt](https://github.com/slap-editor/slap/files/187425/npm-debug_log.txt)

**Comment by Endi1** [comment]
Try updating to the latest stable version of Node.

**Comment by rootscript** [comment]
I'm having problems too, if I install via `sudo npm install -g slap@latest`, and try to run slap I get:
```
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Release/pathwatcher.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/slap/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/slap/node_modules/pathwatcher/lib/main.js:218:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/slap/node_modules/editor-widget/node_modules/text-buffer/lib/text-buffer.js:11:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/slap/node_modules/editor-widget/node_modules/text-buffer/lib/text-buffer.js:1406:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/slap/node_modules/editor-widget/lib/Editor.js:8:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
I have node & npm installed via homebrew:
`npm -v` returns `v4.2.0`
`node -v` returns `v7.8.0`
`npm config get prefix` returns `/usr/local`
running macOS Sierra version 10.12.3

I would really appreciate some help.  ? Do you need me to provide any further info ?
