### ISSUE TITLE
Failed to create new file

### ISSUE THREAD

**Issue by zeg-io** [slap-editor/slap#395]
I attempted to create and edit a new (currently non-existing) file by using

`slap dc-logs.sh`

It just crashed with the following...

```
Fatal Error: ENOENT: no such file or directory, lstat 'dc-logs.sh'
    at Error (native)
    at Object.fs.lstatSync (fs.js:994:11)
    at /usr/lib/node_modules/slap/lib/ui/Slap.js:67:14
    at tryCatcher (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/async.js:143:Fatal Error: ENOENT: no such file or directory, lstat 'dc-logs.sh'
    at Error (native)
    at Object.fs.lstatSync (fs.js:994:11)
    at /usr/lib/node_modules/slap/lib/ui/Slap.js:67:14
    at tryCatcher (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
12)
    at Async._drainQueues (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/slap/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

**Comment by zeg-io** [comment]
I see in the docs that the suggested convention is to just execute the command without a filename, but I submit that entering the filename up front is more intuitive (to me anyhow).
