### ISSUE TITLE
doesn't work with v8.1.2

### ISSUE THREAD

**Issue by imkimchi** [slap-editor/slap#399]
I just updated node version to 8.1.2 and doesn't work since I updated it. 

```
root@inventory:/home/inventory/inventory/server# slap package.json
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/usr/local/lib/node_modules/slap/node_modules/pathwatcher/build/Release/pathwatcher.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/slap/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/slap/node_modules/pathwatcher/lib/main.js:218:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/slap/node_modules/editor-widget/node_modules/text-buffer/lib/text-buffer.js:11:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/slap/node_modules/editor-widget/node_modules/text-buffer/lib/text-buffer.js:1406:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/slap/node_modules/editor-widget/lib/Editor.js:8:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by SolarAquarion** [comment]
It needs the lts version

**Comment by cancerberoSgx** [comment]
the problem seems to be with npm - because I'm having the same error with nodejs-lts but latest npm :

$ node -v
v6.11.1
$  npm -v
5.3.0

If the problem is with npm there is no such a thing as "npm - lts" so the issue would be more "serious" . I'm on archlinux and as a rolling release distribution we need too use latest npm since npm and nodejs are different packages...

**Comment by SolarAquarion** [comment]
I think it needs "argon"

**Comment by ichiriac** [comment]
same, no way to install it :

```
$ npm -v
3.10.8
$ node -v
v7.0.0
$ uname -a
Linux devbox 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Also tried to remove `...slap/node_modules/pathwatcher/build/*` and successfully rebuilds from sources, but still got the same error.

**Comment by dbkaplun** [comment]
```sh
$ npm rm -g slap
$ npm install -g slap
```
Does that fix it?

**Comment by SolarAquarion** [comment]
It's about node versions, can you also add yarn support
