### ISSUE TITLE
"Cannot find module pathwatcher.node'

### ISSUE THREAD

**Issue by geirawsm** [slap-editor/slap#403]
When starting `slap` I get the following error:

    module.js:487
        throw err;
        ^
    
    Error: Cannot find module '../build/Release/pathwatcher.node'
        at Function.Module._resolveFilename (module.js:485:15)
        at Function.Module._load (module.js:437:25)
        at Module.require (module.js:513:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/usr/lib64/node_modules/slap/node_modules/pathwatcher/lib/main.js:6:13)
        at Object.<anonymous> (/usr/lib64/node_modules/slap/node_modules/pathwatcher/lib/main.js:218:4)
        at Module._compile (module.js:569:30)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:503:32)
        at tryModuleLoad (module.js:466:12)
        at Function.Module._load (module.js:458:3)
        at Module.require (module.js:513:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/usr/lib64/node_modules/slap/node_modules/editor-widget/node_modules/text-buffer/lib/text-buffer.js:11:10)
        at Object.<anonymous> (/usr/lib64/node_modules/slap/node_modules/editor-widget/node_modules/text-buffer/lib/text-buffer.js:1406:4)
        at Module._compile (module.js:569:30)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:503:32)
        at tryModuleLoad (module.js:466:12)
        at Function.Module._load (module.js:458:3)
        at Module.require (module.js:513:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/usr/lib64/node_modules/slap/node_modules/editor-widget/lib/Editor.js:8:18)
        at Module._compile (module.js:569:30)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:503:32)
        at tryModuleLoad (module.js:466:12)
        at Function.Module._load (module.js:458:3)

`npm -v` 5.3.0
`node -v` v8.2.1

`uname -a` Linux Solus 4.9.39-35.lts x86_64 GNU/Linux

**Comment by gl00ten** [comment]
Second this.  I installed node on ubuntu using the debian repo.

$ npm -v;node -v;uname -a
5.4.0
v6.11.3
Linux HP-Z230 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dbkaplun** [comment]
```sh
$ npm rm -g slap
$ npm install -g slap
```
Does that fix it?

**Comment by insign** [comment]
5.7.1
v8.10.0
Linux i7 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vzolin** [comment]
Also having the same error

$  npm -v;node -v;uname -a
6.1.0
v8.11.3
Linux BLU365-N0004 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
