### ISSUE TITLE
Root privileges are not enough

### ISSUE THREAD

**Issue by ShalokShalom** [slap-editor/slap#412]
![screenshot_20190220_083859](https://user-images.githubusercontent.com/6344099/53074696-b62ef380-34eb-11e9-97b2-d3cf12ca5e1f.png)

**Comment by babhishek21** [comment]
I have the exact same problem. I tried [this](https://github.com/nodejs/node-gyp/issues/454#issuecomment-315691803) and it only got me so far: `node-gyp` threw a `make` error (**ELIFECYCLE**).

```
5 warnings and 1 error generated.
make: *** [Release/obj.target/marker_index/src/native/marker-index-wrapper.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/11.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/slap/node_modules/marker-index
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! marker-index@4.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the marker-index@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<redacted>/.npm/_logs/2019-03-25T09_34_50_118Z-debug.log
```

**Comment by jcklpe** [comment]
Same. Looks like this project isindeed dead.

**Comment by MuhammadSawalhy** [comment]
See this issue, I have answered it, #414
