### ISSUE TITLE
Can't use npm to install slap

### ISSUE THREAD

**Issue by sam-k** [slap-editor/slap#414]
Trying to install slap using the provided command throws this wonderful error message:

```
samkim@Sams-MacBook-Pro-3 ~ % npm install -g slap@latest 
/usr/local/bin/slap -> /usr/local/lib/node_modules/slap/slap.js

> marker-index@4.0.0 install /usr/local/lib/node_modules/slap/node_modules/marker-index
> node-gyp rebuild

  CXX(target) Release/obj.target/marker_index/src/native/iterator.o
  CXX(target) Release/obj.target/marker_index/src/native/marker-index-wrapper.o
../src/native/marker-index-wrapper.cc:21:172: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(GenerateRandomNumber)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:22:144: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(Insert)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:23:156: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(SetExclusive)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:24:144: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(Delete)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:25:144: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(Splice)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:26:148: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(GetStart)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:27:144: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(GetEnd)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:28:146: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(Compare)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:29:164: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(FindIntersecting)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:30:160: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(FindContaining)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:31:162: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(FindContainedIn)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:32:160: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(FindStartingIn)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:33:156: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(FindEndingIn)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:34:140: error: too few arguments to
      function call, single argument 'context' was not specified
  ...Nan::New<FunctionTemplate>(Dump)->GetFunction());
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:39:98: warning: 'Get' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
  ...= Nan::To<Object>(Nan::GetCurrentContext()->Global()->Get(number_string)...
                                                           ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3457:3: note: 
      'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/native/marker-index-wrapper.cc:40:96: warning: 'Get' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
  ...Get(is_finite_string)).ToLocalChecked()));
     ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3457:3: note: 
      'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/native/marker-index-wrapper.cc:46:95: warning: 'Get' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
  ...= Nan::To<Object>(Nan::GetCurrentContext()->Global()->Get(set_string)).T...
                                                           ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3457:3: note: 
      'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/native/marker-index-wrapper.cc:47:80: warning: 'Get' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
  ...set_prototype_local = Nan::To<Object>(set_constructor_local->Get(prototy...
                                                                  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3457:3: note: 
      'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/native/marker-index-wrapper.cc:48:79: warning: 'Get' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
  ...set_add_method_local = Nan::To<Object>(set_prototype_local->Get(add_stri...
                                                                 ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3457:3: note: 
      'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/native/marker-index-wrapper.cc:62:50: error: too few arguments to
      function call, single argument 'context' was not specified
                constructorTemplate->GetFunction());
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:5995:3: note: 
      'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:96:67: warning: 'Get' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
    Nan::MaybeLocal<Integer> maybe_row = Nan::To<Integer>(object->Get(Na...
                                                                  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3457:3: note: 
      'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/native/marker-index-wrapper.cc:103:70: warning: 'Get' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
    Nan::MaybeLocal<Integer> maybe_column = Nan::To<Integer>(object->Get(Nan...
                                                                     ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3457:3: note: 
      'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/native/marker-index-wrapper.cc:112:54: error: too few arguments to
      function call, single argument 'context' was not specified
      row = static_cast<unsigned>(js_row->Int32Value());
                                  ~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:2613:3: note: 
      'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:118:60: error: too few arguments to
      function call, single argument 'context' was not specified
      column = static_cast<unsigned>(js_column->Int32Value());
                                     ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:2613:3: note: 
      'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:128:92: error: too few arguments to
      function call, expected 4, have 3
  ...= Nan::New(is_finite_function)->CallAsFunction(Nan::Null(), 1, argv);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3789:3: note: 
      'CallAsFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> CallAsFunction(Local<Context> context,
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:351:31: note: 
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/native/marker-index-wrapper.cc:129:20: error: no matching member function
      for call to 'BooleanValue'
    return result->BooleanValue();
           ~~~~~~~~^~~~~~~~~~~~
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:2603:8: note: 
      candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:2606:51: note: 
      candidate function not viable: requires single argument 'context', but no
      arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
../src/native/marker-index-wrapper.cc:134:13: warning: 'Set' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
    result->Set(Nan::New(row_string), Nan::New<Integer>(point.row));
            ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3402:3: note: 
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/native/marker-index-wrapper.cc:135:13: warning: 'Set' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
    result->Set(Nan::New(column_string), Nan::New<Integer>(point.column));
            ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3402:3: note: 
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/native/marker-index-wrapper.cc:157:14: warning: 'Set' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
      range->Set(Nan::New(start_string), PointToJS(pair.second.start));
             ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3402:3: note: 
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/native/marker-index-wrapper.cc:158:14: warning: 'Set' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
      range->Set(Nan::New(end_string), PointToJS(pair.second.end));
             ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3402:3: note: 
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/native/marker-index-wrapper.cc:159:22: warning: 'Set' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
      result_object->Set(Nan::New<Integer>(pair.first), range);
                     ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3402:3: note: 
      'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/samkim/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: 
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
12 warnings and 20 errors generated.
make: *** [Release/obj.target/marker_index/src/native/marker-index-wrapper.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/12.11.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/slap/node_modules/marker-index
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"12.11.1","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! marker-index@4.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the marker-index@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samkim/.npm/_logs/2019-11-09T07_50_02_012Z-debug.log
```

**Comment by tomekc** [comment]
Looks like newer Node.js are unsupported. Switching back to **8.x** helped, but it's hardly a solution.

**Comment by MuhammadSawalhy** [comment]
***Update***
 
It turns out that the issue is caused by `editor-widget@1.1.1`, which requires `text-buffer@8.0.6`, which also depends on packages. One of these packages is `pathwatcher@6.6.2`, all the story begins here so that we see all of these errors.

I used `nodejs@6`.

----------

***Before Update***

The issue is with `node-inspect`, which is installed by default with the newer version of nodejs, we now are using `node inspect /path/to/file.js`.
```json
    // ....
    "node-inspector": "0.12.8",
    // ....
```

I have cloned this repo and installed each package separately until I reach `node-inspect` which requires some C++ code for V8 engine to be built.

-------------------

Dependencies

```bash
> # dependencies
> npm install base-widget@1.1.0 blessed@0.1.81 \
          bluebird@3.4.1 editor-widget@1.1.1 lodash@4.14.1 \
          mkdirp@0.5.1 node-clap@0.0.5 rc@1.1.6 \
          slap-util@1.0.7 ttys@0.0.3 update-notifier@1.0.3
```

-----------

Dev-Dependencies

```bash
> # devDependencies
> npm get-random-port@0.0.1 istanbul@^0.4.4 tape@^4.6.3
```

**Comment by MuhammadSawalhy** [comment]
> _**Update**_
> 
> It turns out that the issue is caused by `editor-widget@1.1.1`, which requires `text-buffer@8.0.6`, which also depends on packages. One of these packages is `pathwatcher@6.6.2`, all the story begins here so that we see all of these errors.
> 

Alhamdulillah, I got it working after a long journey 💖.

![image](https://user-images.githubusercontent.com/42011920/104824721-f8d6e300-585c-11eb-904b-4d926d84541e.png)
